import express from 'express';
import { handlePaymentWebhook } from '../../webhooks/paymentWebhook.js';
import { asyncHandler } from '../../utils/asyncHandler.js';

export const webhookRouter = express.Router();

/**
 * @swagger
 * tags:
 *   name: Webhooks
 *   description: Payment provider webhook endpoints
 */

/**
 * @swagger
 * /v1/webhooks/razorpay:
 *   post:
 *     summary: Handle Razorpay webhook events
 *     tags: [Webhooks]
 *     description: Receives Razorpay payment lifecycle events and updates payment and invoice status.
 *     security: []
 *     parameters:
 *       - in: header
 *         name: x-razorpay-signature
 *         required: true
 *         schema:
 *           type: string
 *         description: HMAC SHA-256 signature generated by Razorpay using the webhook secret.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               id:
 *                 type: string
 *                 example: evt_razorpay_001
 *               event:
 *                 type: string
 *                 enum: [payment.captured, payment.failed]
 *               payload:
 *                 type: object
 *                 properties:
 *                   payment:
 *                     type: object
 *                     properties:
 *                       entity:
 *                         type: object
 *                         properties:
 *                           order_id:
 *                             type: string
 *                             example: order_Q1a2b3c4d5
 *                           id:
 *                             type: string
 *                             example: pay_Q1a2b3c4d5
 *     responses:
 *       200:
 *         description: Webhook processed successfully
 *       400:
 *         description: Invalid signature or malformed payload
 *       404:
 *         description: Matching payment record not found
 *       500:
 *         description: Webhook secret is not configured
 */

// Mock provider webhook endpoint that accepts JSON payloads.
webhookRouter.post('/payment', asyncHandler(handlePaymentWebhook));
